//Placeholder data for the about page
const AboutData = {
  Name: "Jane Doe",
  Title: "Full Stack Developer",
  LinkedIn: "www.google.com",
  GitHub: "www.google.com",
  YouTube: "www.google.com",
  Twitter: "www.google.com",
  Twitch: "www.google.com",
  Instagram: "www.google.com",
  Facebook: "www.google.com",
  Rumble: "www.google.com",
  ProgrammingLang: [
    "Javascript",
    "Typescript",
    "C#",
    "Python",
    "Java",
    "HTML",
    "CSS",
    "SQL",
    "NoSQL",
    "Jquery",
  ],
  Frameworks: [
    "React",
    "Node",
    "Express",
    "Next",
    "Babylon.js",
    "Bootstrap",
    "ASP.Net",
    "EntityFramework",
    "Xamarin",
    "Dot net Maui",
  ],
  Skills: [
    "Full Stack Development",
    "Front End Development",
    "Back End Development",
    "Mobile Development",
    "Game Development",
    "Database Management",
    "UI/UX Design",
    "Project Management",
  ],
  BrandStatment:
    "I am a full stack developer with experience in web, mobile, and game development. I have a passion for creating and designing applications that are both functional and visually appealing. I have experience in a variety of programming languages and frameworks, and I am always eager to learn new technologies and expand my skill set. I am a team player with strong communication and problem-solving skills, and I am always looking for new opportunities to grow and develop as a developer.",
  AboutMeHobbies:
    "I enjoy playing video games, reading, and spending time with my family and friends. I am also a huge fan of anime and manga, and I love to draw and create my own characters and stories. I am a creative and imaginative person, and I am always looking for new ways to express myself and share my ideas with others.",
  Education: "",
  Contact: "user@user.com",
  Resume:
    "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
};
export default AboutData;
