//placeholder for projects data
const PortfolioProjects = [
  {
    id: "1",
    category: ["Web"],
    ProjectName: "Umami",
    TechStack: ["React", "Node", "Express", "MongoDB", "Next UI"],
    Language: "TypeScript",
    ProjectDescription:
      "Umami is a app that helps home chefs to find recipes and create a shopping list.",
    Links: ["www.google.com", "www.google.com"],
    ProjectImage: [
      "https://placehold.co/200",
      "https://placehold.co/200",
      "https://placehold.co/200",
    ],
  },
  {
    id: "2",
    category: ["Game", "Web"],
    ProjectName: "Raid Encouter Trainer",
    TechStack: [
      "React",
      "Node",
      "Express",
      "MongoDB",
      "Next UI",
      "Colussus",
      "Babylon.js",
    ],
    Language: "TypeScript",
    ProjectDescription:
      "Raid Encounter Trainer is a app that helps gamers to learn and practice raid encounters in Final Fantasy 14.",
    Links: ["www.google.com", "www.google.com"],
    ProjectImage: [
      "https://placehold.co/200",
      "https://placehold.co/200",
      "https://placehold.co/200",
      "https://placehold.co/200",
    ],
  },
  {
    id: "3",
    category: ["Game", "Web"],
    ProjectName: "Role Playing Game",
    TechStack: [
      "React",
      "Node",
      "Express",
      "MongoDB",
      "Babylon.js",
      "Bootstrap",
    ],
    Language: "TypeScript",
    ProjectDescription:
      "A basic role playing game with turn based startegy elements.",
    Links: ["www.google.com", "www.google.com"],
    ProjectImage: [
      "https://placehold.co/200",
      "https://placehold.co/200",
      "https://placehold.co/200",
      "https://placehold.co/200",
      "https://placehold.co/200",
    ],
  },
  {
    id: "4",
    category: ["Desktop", "Mobile"],
    ProjectName: "Knight's Watch",
    TechStack: ["Dot net Maui", "ASP.Net", "EntityFramework", "SQL", "Xamarin"],
    Language: "C#",
    ProjectDescription:
      "A mobile app that helps people to find and report crime in their area.",
    Links: ["www.google.com", "www.google.com"],
    ProjectImage: [
      "https://placehold.co/200",
      "https://placehold.co/200",
      "https://placehold.co/200",
      "https://placehold.co/200",
    ],
  },
  {
    id: "5",
    category: ["Web"],
    ProjectName: "Open Kaban",
    TechStack: ["React", "Node", "Express", "MongoDB", "Next UI"],
    Language: "TypeScript",
    ProjectDescription: "A open source project management tool.",
    Links: ["www.google.com", "www.google.com"],
    ProjectImage: ["https://placehold.co/200", "https://placehold.co/200"],
  },
  {
    id: "6",
    category: ["Music"],
    ProjectName: "Music Player",
    TechStack: [],
    Language: "",
    ProjectDescription: "Djent Ablum",
    Links: ["www.google.com", "www.google.com"],
    ProjectImage: [
      "https://placehold.co/200",
      "https://placehold.co/200",
      "https://placehold.co/200",
      "https://placehold.co/200",
      "https://placehold.co/200",
      "https://placehold.co/200",
    ],
  },
  {
    id: "7",
    category: ["3D Art"],
    ProjectName: "3D Model",
    TechStack: [],
    Language: "",
    ProjectDescription: "3D Model of a car",
    Links: ["www.google.com", "www.google.com"],
    ProjectImage: ["https://placehold.co/200"],
  },
  {
    id: "8",
    category: ["Game"],
    ProjectName: "Game",
    TechStack: ["Unity", "C#"],
    Language: "C#",
    ProjectDescription: "A basic game",
    Links: ["www.google.com", "www.google.com"],
    ProjectImage: ["https://placehold.co/200", "https://placehold.co/200"],
  },
  {
    id: "9",
    category: ["Game"],
    ProjectName: "Game",
    TechStack: ["Unreal Engine", "C++"],
    Language: "C++",
    ProjectDescription: "A basic game",
    Links: ["www.google.com", "www.google.com"],
    ProjectImage: ["https://placehold.co/200"],
  },
  {
    id: "10",
    category: ["Music"],
    ProjectName: "Music II",
    TechStack: [],
    Language: "",
    ProjectDescription: "D & D concept album",
    Links: ["www.google.com", "www.google.com"],
    ProjectImage: ["https://placehold.co/200"],
  },
];

export default PortfolioProjects;
