//placeholder for projects data
const PortfolioProjects = [
  {
    id: "1",
    category: ["Web"],
    ProjectName: "Umami",
    TechStack: ["React", "Node", "Express", "MongoDB", "Next UI"],
    Language: "TypeScript",
    ProjectDescription:
      "Umami is a app that helps home chefs to find recipes and create a shopping list.",
    Shortdescription: "A recipe app",
    Links: ["www.google.com", "www.google.com"],
    ProjectImage: [
      "https://placehold.co/200",
      "https://placehold.co/200",
      "https://placehold.co/200",
    ],
  },
  {
    id: "2",
    category: ["Game", "Web"],
    ProjectName: "Raid Encouter Trainer",
    TechStack: [
      "React",
      "Node",
      "Express",
      "MongoDB",
      "Next UI",
      "Colussus",
      "Babylon.js",
    ],
    Language: "TypeScript",
    ProjectDescription:
      "Raid Encounter Trainer is a app that helps gamers to learn and practice raid encounters in Final Fantasy 14.",
    Shortdescription: "A raid encounter trainer",
    Links: ["www.google.com", "www.google.com"],
    ProjectImage: [
      "https://placehold.co/200",
      "https://placehold.co/200",
      "https://placehold.co/200",
      "https://placehold.co/200",
    ],
  },
  {
    id: "3",
    category: ["Game", "Web"],
    ProjectName: "Role Playing Game",
    TechStack: [
      "React",
      "Node",
      "Express",
      "MongoDB",
      "Babylon.js",
      "Bootstrap",
    ],
    Language: "TypeScript",
    ProjectDescription:
      "A basic role playing game with turn based startegy elements.",
    Shortdescription: "A role playing game",
    Links: ["www.google.com", "www.google.com"],
    ProjectImage: [
      "https://placehold.co/200",
      "https://placehold.co/200",
      "https://placehold.co/200",
      "https://placehold.co/200",
      "https://placehold.co/200",
    ],
  },
  {
    id: "4",
    category: ["Desktop", "Mobile"],
    ProjectName: "Knight's Watch",
    TechStack: ["Dot net Maui", "ASP.Net", "EntityFramework", "SQL", "Xamarin"],
    Language: "C#",
    ProjectDescription:
      "A mobile app that helps people to find and report crime in their area.",
    Shortdescription: "A crime reporting app",
    Links: ["www.google.com", "www.google.com"],
    ProjectImage: [
      "https://placehold.co/200",
      "https://placehold.co/200",
      "https://placehold.co/200",
      "https://placehold.co/200",
    ],
  },
  {
    id: "5",
    category: ["Web"],
    ProjectName: "Open Kaban",
    TechStack: ["React", "Node", "Express", "MongoDB", "Next UI"],
    Language: "TypeScript",
    ProjectDescription: "A open source project management tool.",
    Shortdescription: "A project management tool",
    Links: ["www.google.com", "www.google.com"],
    ProjectImage: ["https://placehold.co/200", "https://placehold.co/200"],
  },
  {
    id: "6",
    category: ["Music"],
    ProjectName: "Music Player",
    TechStack: ["Reaper"],
    Language: "Reaper",
    ProjectDescription: "Djent Ablum",
    Shortdescription: "A music player",
    Links: ["www.google.com", "www.google.com"],
    ProjectImage: [
      "https://placehold.co/200",
      "https://placehold.co/200",
      "https://placehold.co/200",
      "https://placehold.co/200",
      "https://placehold.co/200",
      "https://placehold.co/200",
    ],
  },
  {
    id: "7",
    category: ["3D Art"],
    ProjectName: "3D Model",
    TechStack: ["Blender"],
    Language: "Blender",
    ProjectDescription: "3D Model of a car",
    Shortdescription: "A 3D model",
    Links: ["www.google.com", "www.google.com"],
    ProjectImage: ["https://placehold.co/200"],
  },
  {
    id: "8",
    category: ["Game"],
    ProjectName: "Game",
    TechStack: ["Unity", "C#"],
    Language: "C#",
    ProjectDescription: "A basic game",
    Shortdescription: "A basic game",
    Links: ["www.google.com", "www.google.com"],
    ProjectImage: ["https://placehold.co/200", "https://placehold.co/200"],
  },
  {
    id: "9",
    category: ["Game"],
    ProjectName: "Game",
    TechStack: ["Unreal Engine", "C++"],
    Language: "C++",
    ProjectDescription: "A basic game",
    Shortdescription: "A basic game",
    Links: ["www.google.com", "www.google.com"],
    ProjectImage: ["https://placehold.co/200"],
  },
  {
    id: "10",
    category: ["Music"],
    ProjectName: "Music II",
    TechStack: ["Reaper"],
    Language: "Reaper",
    ProjectDescription: "D & D concept album",
    Shortdescription: "A music album",
    Links: ["www.google.com", "www.google.com"],
    ProjectImage: ["https://placehold.co/200"],
  },
];

export default PortfolioProjects;

const Categories = [
  "Web",
  "Game",
  "Desktop",
  "Mobile",
  "Music",
  "3D Art",
  "All",
];

export { Categories };
